// <auto-generated />
using System;
using BacheloretteApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BacheloretteApi.Migrations
{
    [DbContext(typeof(BacheloretteApiContext))]
    [Migration("20210622015107_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BacheloretteApi.Models.Bachelorette", b =>
                {
                    b.Property<int>("BacheloretteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Hometown")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Job")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.HasKey("BacheloretteId");

                    b.ToTable("Bachelorettes");
                });

            modelBuilder.Entity("BacheloretteApi.Models.Contestant", b =>
                {
                    b.Property<int>("ContestantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BacheloretteId")
                        .HasColumnType("int");

                    b.Property<string>("Hometown")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Job")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int>("WeeksIn")
                        .HasColumnType("int");

                    b.HasKey("ContestantId");

                    b.HasIndex("BacheloretteId");

                    b.ToTable("Contestants");
                });

            modelBuilder.Entity("BacheloretteApi.Models.Contestant", b =>
                {
                    b.HasOne("BacheloretteApi.Models.Bachelorette", "Bachelorette")
                        .WithMany("Contestants")
                        .HasForeignKey("BacheloretteId");

                    b.Navigation("Bachelorette");
                });

            modelBuilder.Entity("BacheloretteApi.Models.Bachelorette", b =>
                {
                    b.Navigation("Contestants");
                });
#pragma warning restore 612, 618
        }
    }
}
